AMBIGUO = [
    {
        "doc_id": "GOLD-AMB-01",
        "test_type": "ambiguo",
        "title": "Arquitectura Híbrida de Inferencia de Inteligencia Artificial Serverless mediante AWS Lambda y GitHub Actions CI/CD",
        "content": "Contexto Operativo Multi-Dominio: En esta compleja solución arquitectónica, los diferentes dominios tecnológicos convergen en un único microservicio. Logramos integrar exitosamente un modelo fundacional de clasificación semántica, que fue entrenado previamente con scripts intensivos en Python y PyTorch, empaquetándolo minuciosamente dentro de un contenedor Docker liviano y altamente optimizado. Sin embargo, el centro del proceso radica en cómo esta imagen contenedorizada se provisiona y orquesta de forma totalmente desatendida. Una compleja tubería (pipeline) de Integración Continua y Despliegue Continuo (CI/CD) orquestada en los servidores de GitHub Actions toma el código fuente, lo compila sin intervención humana y desencadena el paso a producción. Finalmente, el artefacto resultante se despliega de forma nativa como una función Serverless elástica en el entorno de AWS Lambda. Esta función sin servidor permanece inactiva, reduciendo costos drásticamente, hasta que es invocada transaccionalmente por eventos de peticiones HTTP en tiempo real provenientes del servicio administrado de Amazon API Gateway, logrando alta disponibilidad global.",
        "expected_category": "AI/ML",
    },
    {
        "doc_id": "GOLD-AMB-02",
        "test_type": "ambiguo",
        "title": "Microservicio Reactivo de Backend en Spring Boot 3 con Acoplamiento a Data Lakes distribuidos S3 e Identidad KMS",
        "content": "Flujo de Datos y Abstracción de Código: Construimos una infraestructura de Application Programming Interface (API) de excepcional rendimiento, desarrollada en su integridad utilizando el ecosistema de Java 21 LTS y el framework reactivo de Spring Boot (WebFlux). Esta pieza de software (Backend) se desliga de la base de datos relacional tradicional y se conecta directamente a un almacenamiento masivo de objetos en la nube de Amazon Web Services (AWS S3) comportándose como un potente Data Lake. La lógica del backend implementa una serie de consultas directas, proyecciones asíncronas y agregaciones analíticas sobre inmensos volúmenes de archivos parquet crudos. Para garantizar el absoluto hermetismo de los datos personales (PII) bajo las normas GDPR corporativas, los flujos de lectura y escritura ejecutan llamadas criptográficas interconectándose en milisegundos con las claves simétricas del servicio AWS KMS, orquestado todo bajo políticas IAM de extremo menor privilegio que el framework debe firmar criptográficamente antes de cada Request.",
        "expected_category": "Backend",
    },
    {
        "doc_id": "GOLD-AMB-03",
        "test_type": "ambiguo",
        "title": "Optimización del Pipeline de Ingestión de Datos ETL Distribuido mediante Pods Elásticos y Argo Workflows en Kubernetes",
        "content": "Desafíos de Sincronización y Procesamiento Masivo: El equipo de especialistas en plataforma de infraestructura diseñó y programó un flujo de procesamiento determinista (DAG) capaz de absorber y procesar cientos de millones de registros transaccionales asíncronos generados diariamente por los microservicios de pago. La solución arquitectónica central se aparta del enfoque clásico de scripts estáticos, operando en lugar de ello como una constelación de pods distribuidos de Kubernetes orquestados estrechamente mediante Argo Workflows. Este orquestador cloud-native dispara bajo demanda tareas transitorias masivamente paralelas (workers) en el motor de clúster distribuido Apache Spark, encargadas de extraer grandes porciones de datos no estructurados en formato crudo, transformarlos bajo estrictas reglas de normalización y cargarlos sintácticamente validados al repositorio tabular maestro de Snowflake, garantizando tolerancia a las caídas de hardware.",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-AMB-04",
        "test_type": "ambiguo",
        "title": "Dashboard Web Frontend en React con Visualización en Tiempo Real de Métricas de MLOps",
        "content": "Desarrollamos un panel de control interactivo en el frontend utilizando React, TypeScript y bibliotecas de gráficos D3.js. La interfaz visualiza en tiempo real las métricas de rendimiento de los modelos de aprendizaje automático (F1-Score, matriz de confusión y desviaciones del dataset de prueba). En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Frontend",
    },
    {
        "doc_id": "GOLD-AMB-05",
        "test_type": "ambiguo",
        "title": "Pipeline de Ingestión de Datos Masivos ETL Orquestado en Kubernetes con Argo Workflows",
        "content": "El equipo de ingeniería de datos diseñó un flujo de trabajo para procesar millones de transacciones diarias. La solución ejecuta pods de Kubernetes coordinados por Argo Workflows que lanzan tareas distribuidas en Apache Spark para transformar datos no estructurados. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-AMB-06",
        "test_type": "ambiguo",
        "title": "Escaneo de Seguridad DevSecOps Automatizado sobre Contenedores Docker en GitHub Actions",
        "content": "Para fortalecer la postura de seguridad, incorporamos análisis estático de código fuente (SAST) con SonarQube y escaneo de vulnerabilidades en imágenes Docker con Trivy directamente dentro del pipeline de integración continua en GitHub Actions, bloqueando el despliegue ante fallos críticos. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Security",
    },
    {
        "doc_id": "GOLD-AMB-07",
        "test_type": "ambiguo",
        "title": "Microservicio de Recomendación Personalizada en FastAPI con Inferencia scikit-learn",
        "content": "Un microservicio backend ligero desarrollado en Python con FastAPI recibe las solicitudes de recomendación de contenido, carga el modelo matricial serializado de scikit-learn y retorna una respuesta JSON estructurada en menos de 10 milisegundos. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Backend",
    },
    {
        "doc_id": "GOLD-AMB-08",
        "test_type": "ambiguo",
        "title": "Monitoreo Cloud de Seguridad y Detección de Amenazas en Clusters de AWS EKS",
        "content": "Desplegamos agentes de seguridad de Falco dentro del cluster de Kubernetes AWS EKS para capturar llamadas al sistema anómalas en tiempo real. Los eventos sospechosos se envían a través de Promtail hacia una pila centralizada de Elasticsearch para su auditoría. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Cloud",
    },
    {
        "doc_id": "GOLD-AMB-09",
        "test_type": "ambiguo",
        "title": "Preprocesamiento Masivo de Corpus de Texto para Entrenamiento de Modelos LLM Transformer",
        "content": "Previo a la fase de entrenamiento del modelo de lenguaje, se desarrolló un pipeline de datos en PySpark que limpia carácteres inválidos, remueve stop-words y tokeniza miles de millones de documentos técnicos conservando la estructura semántica original. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-AMB-10",
        "test_type": "ambiguo",
        "title": "Librería Móvil Nativa en Kotlin para Autenticación Biométrica y Comunicación Cifrada TLS",
        "content": "Creamos un módulo nativo para Android utilizando el lenguaje Kotlin que abstrae la verificación mediante huella dactilar (BiometricPrompt) e impone la validación de certificados SSL Pinning en todas las conexiones de red HTTPS. En el marco de la modernización de la plataforma, este componente fue refactorizado para garantizar un rendimiento óptimo bajo cargas de trabajo pesadas. El equipo de arquitectura técnica documentó cada decisión de diseño para asegurar que el despliegue a producción cumpla con todos los estándares de calidad ISO y las regulaciones corporativas vigentes de protección de datos (GDPR).",
        "expected_category": "Mobile",
    }
]
