CASOS_LIMITE = [
    {
        "doc_id": "GOLD-LIM-01",
        "test_type": "casos_limite",
        "title": "   ",
        "content": "                                                                                        ",
        "expected_category": "DevOps",
    },
    {
        "doc_id": "GOLD-LIM-02",
        "test_type": "casos_limite",
        "title": "??? !!! ### $$$ %%% ^^^ &&& *** ((( ))) ___ +++ ===",
        "content": "@@@ $$$ %%% ^^^ &&& *** ((( ))) ___ +++ === {{{ }}} ::: <<< >>> ??? ~~~ ``` ||| \\\\\\ ///",
        "expected_category": "Security",
    },
    {
        "doc_id": "GOLD-LIM-03",
        "test_type": "casos_limite",
        "title": "🚀🤖📊 Cloud AI Machine Learning Kubernetes Docker Python Data Security Backend Frontend Mobile",
        "content": "🤖 ML ⚡ AWS 🔐 Security 💻 Java 📱 iOS 🌐 Frontend 🐘 PostgreSQL 🐳 Docker 📊 Spark ⚡ FastAPI 🛠️ Terraform ⚙️ CI/CD 🚀 Next.js",
        "expected_category": "AI/ML",
    },
    {
        "doc_id": "GOLD-LIM-04",
        "test_type": "casos_limite",
        "title": "a",
        "content": "b",
        "expected_category": "Backend",
    },
    {
        "doc_id": "GOLD-LIM-05",
        "test_type": "casos_limite",
        "title": '\"\"\"Texto con comillas dobles y comillas simples anidadas\'\'\'',
        "content": "SELECT * FROM users WHERE title = 'SELECT 1 FROM table WHERE id = 100';",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-LIM-06",
        "test_type": "casos_limite",
        "title": "1234567890 9876543210 000000000 111111111 222222222",
        "content": "100 200 500 1000 2500 5000 7500 10000 3.1415926535 2.7182818284 42 0 1000000 9999999",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-LIM-07",
        "test_type": "casos_limite",
        "title": "Unicode International Text Test: 日本語 中文 Русский العربية עברית हिन्दी Español Français",
        "content": "El sistema procesa texto internacional multilenguaje: こんにちは 世界, Привет мир, Hello world, Hola mundo, 大家好.",
        "expected_category": "Frontend",
    },
    {
        "doc_id": "GOLD-LIM-08",
        "test_type": "casos_limite",
        "title": "# H1 Header\\n## H2 Subheader\\n### H3 Section\\n#### H4 Subsection",
        "content": "- Bullet 1\\n- Bullet 2\\n- Bullet 3\\n\\nCode snippet:\\ndef hello_world():\\n    print('hello world')\\n\\n| Table | Header |\\n|-------|--------|\\n| Val1  | Val2   |",
        "expected_category": "DevOps",
    },
    {
        "doc_id": "GOLD-LIM-09",
        "test_type": "casos_limite",
        "title": "SQL Injection & XSS Attack Payload Test String: ' OR '1'='1",
        "content": "' OR 1=1; DROP TABLE users; -- <script>alert('XSS Attack Execution')</script> <iframe src=\\\"javascript:alert(1)\\\"></iframe>",
        "expected_category": "Security",
    },
    {
        "doc_id": "GOLD-LIM-10",
        "test_type": "casos_limite",
        "title": "Mobile App UI Test Android iOS Flutter React Native Swift Kotlin Repetitive Test String",
        "content": "Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile Mobile",
        "expected_category": "Mobile",
    }
]
