CORTOS = [
    {
        "doc_id": "GOLD-CORT-01",
        "test_type": "corto",
        "title": "Pipeline de Integración Continua (CI) con GitHub Actions y Análisis de Calidad en AyniKortex",
        "content": "Contexto de Negocio: En AyniKortex, la velocidad de entrega de nuevas funcionalidades es crítica para mantener la ventaja competitiva en el mercado de plataformas de recursos humanos. Sin embargo, esta velocidad no debe comprometer la calidad del código, razón por la cual el equipo de plataforma ha priorizado la automatización del flujo de despliegue.\\n\\nImplementación Técnica: Para lograr una entrega continua confiable, hemos configurado un pipeline de GitHub Actions que se dispara automáticamente ante cada push o pull request dirigido a la rama main. Este flujo automatizado no solo compila el código fuente y ejecuta las pruebas unitarias con cobertura superior al 85%, sino que integra SonarQube para el análisis estático de vulnerabilidades y code smells. Tras la validación exitosa, el pipeline procede a empaquetar el microservicio de autenticación en una imagen de contenedor Docker, la cual es versionada y empujada a un repositorio privado en Amazon Elastic Container Registry (ECR), dejando el artefacto listo para la orquestación posterior.",
        "expected_category": "DevOps",
    },
    {
        "doc_id": "GOLD-CORT-02",
        "test_type": "corto",
        "title": "Estrategia de Indexación B-Tree y Optimización de Consultas SELECT en PostgreSQL para Alta Concurrencia",
        "content": "Contexto Operativo: A medida que el volumen de documentos indexados en el sistema AyniKortex creció exponencialmente, detectamos una severa degradación en el rendimiento durante los picos de tráfico en horario laboral, afectando la experiencia de los reclutadores al buscar perfiles y CVs.\\n\\nResolución Técnica: El análisis del plan de ejecución mediante EXPLAIN ANALYZE reveló que el motor de base de datos PostgreSQL estaba recurriendo a costosos escaneos secuenciales (Sequential Scans) sobre tablas con millones de registros. Para solventar este cuello de botella, diseñamos e implementamos índices compuestos de tipo B-Tree enfocados en las columnas más consultadas en los filtros WHERE (tales como document_id, status y category). Adicionalmente, aplicamos índices parciales que excluyen registros obsoletos, reduciendo el tamaño del índice en memoria RAM. Estas optimizaciones de Data Engineering disminuyeron el tiempo promedio de respuesta de 450 milisegundos a apenas 12 milisegundos.",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-CORT-03",
        "test_type": "corto",
        "title": "Arquitectura de Redes Neuronales Convolucionales (CNN) en PyTorch para Clasificación Visual",
        "content": "Objetivo del Modelo: Como parte de la validación biométrica y de documentos de identidad en el onboarding de candidatos, AyniKortex requiere un modelo capaz de clasificar imágenes con alta precisión y latencia mínima.\\n\\nDesarrollo Técnico: Diseñamos una arquitectura de red neuronal convolucional personalizada desde cero utilizando el framework PyTorch. El diseño se compone de tres bloques secuenciales de extracción de características, combinando capas convolucionales 2D, funciones de activación ReLU para la no linealidad y agrupamiento espacial mediante Max Pooling. Para el proceso de optimización durante la fase de backpropagation, seleccionamos AdamW, el cual previene el sobreajuste mediante una penalización efectiva de pesos, acoplado a una estrategia de decaimiento de la tasa de aprendizaje mediante Cosine Annealing. El modelo fue entrenado durante 50 épocas en hardware acelerado por GPU, logrando una tasa de falsos positivos inferior al 0.5%.",
        "expected_category": "AI/ML",
    },
    {
        "doc_id": "GOLD-CORT-04",
        "test_type": "corto",
        "title": "Implementación de Autenticación Stateless y Seguridad de APIs con JSON Web Tokens (JWT)",
        "content": "Requisito de Seguridad: Mantener el estado de las sesiones de miles de usuarios concurrentes en la memoria del servidor no es escalable bajo una arquitectura de microservicios efímeros. Se requería un mecanismo seguro y descentralizado para validar la identidad de las peticiones web.\\n\\nSolución de Autenticación: La arquitectura de seguridad del backend se rediseñó utilizando el estándar JSON Web Tokens (JWT) integrado con Spring Security. Al iniciar sesión, el servidor genera un token codificado que incluye claims específicos del usuario, firmado digitalmente mediante un algoritmo asimétrico RSA-256 para evitar su manipulación. El cliente almacena este token de manera segura y lo adjunta en el encabezado 'Authorization: Bearer' de cada solicitud HTTP subsiguiente. Un filtro de seguridad intercepta estas llamadas, verifica matemáticamente la firma del JWT contra la llave pública sin necesidad de consultar la base de datos, logrando una arquitectura 100% Stateless que mitiga vulnerabilidades de suplantación.",
        "expected_category": "Security",
    },
    {
        "doc_id": "GOLD-CORT-05",
        "test_type": "corto",
        "title": "Gestión Predictiva del Estado y Patrón Observer en Aplicaciones React Native TypeScript",
        "content": "Desafío de Interfaz: Las aplicaciones móviles multiplataforma enfrentan el reto de mantener sincronizado el estado visual de la aplicación con la base de datos remota sin bloquear el hilo principal de renderizado (Main UI Thread), especialmente bajo condiciones de red inestables.\\n\\nArquitectura Frontend Móvil: Para la app AyniKortex, estructuramos el ecosistema en React Native y TypeScript aplicando el patrón Redux Toolkit en combinación con RTK Query. Este enfoque nos proporciona un control granular sobre la caché de la red y permite una sincronización en segundo plano mediante mutaciones optimistas (Optimistic Updates). Cuando un usuario interactúa con la interfaz, los componentes visuales reaccionan instantáneamente a los cambios del store global de Redux, delegando las llamadas a las APIs RESTful a manejadores asíncronos. Esta arquitectura garantiza una tasa constante de 60 cuadros por segundo (FPS) en dispositivos Android e iOS, ofreciendo una experiencia excepcionalmente fluida.",
        "expected_category": "Mobile",
    },
    {
        "doc_id": "GOLD-CORT-06",
        "test_type": "corto",
        "title": "Patrón MVC y Arquitectura de Controladores RESTful con Manejo Global de Excepciones en Spring Boot",
        "content": "Contexto Arquitectónico: Un backend robusto debe no solo exponer funcionalidades a través de endpoints, sino también garantizar que cualquier fallo interno sea capturado y traducido en respuestas HTTP estándar, sin filtrar información sensible del sistema al cliente (Stack Traces).\\n\\nDiseño del Backend: La capa de exposición de AyniKortex se implementó utilizando Spring Boot MVC bajo estrictos principios RESTful. Los controladores Java, marcados con la anotación @RestController, actúan únicamente como orquestadores que delegan la lógica de negocio a los servicios de dominio. Utilizamos MapStruct para la conversión eficiente entre Entidades JPA y Data Transfer Objects (DTOs), junto con Jakarta Validation (@Valid) para validar las cargas útiles entrantes. Fundamentalmente, incorporamos un @ControllerAdvice que intercepta todas las excepciones lanzadas en tiempo de ejecución, transformándolas en objetos JSON estructurados con códigos HTTP apropiados (como 400 Bad Request o 404 Not Found), estandarizando así el contrato de comunicación con el frontend.",
        "expected_category": "Backend",
    },
    {
        "doc_id": "GOLD-CORT-07",
        "test_type": "corto",
        "title": "Automatización Declarativa de Clusters EKS y Grupos de Autoescalado en AWS mediante Terraform",
        "content": "Necesidad de Infraestructura: La gestión manual de recursos en la nube conduce invariablemente a la inconsistencia entre entornos (Drift de configuración) y dificulta la recuperación ante desastres en arquitecturas de alta disponibilidad.\\n\\nAprovisionamiento Cloud: Adoptamos un enfoque estricto de Infraestructura como Código (IaC) utilizando Terraform para aprovisionar el entorno base de Kubernetes. El código declarativo de Terraform define un cluster de Elastic Kubernetes Service (Amazon EKS) distribuido a lo largo de tres Zonas de Disponibilidad (Multi-AZ) para garantizar redundancia. Para optimizar los costos computacionales, se configuraron Managed Node Groups integrados con Auto Scaling Groups (ASG) de AWS. Estos grupos monitorizan métricas críticas de reserva de CPU y Memoria, añadiendo o retirando dinámicamente instancias EC2 del pool de nodos subyacente según las demandas de las cargas de trabajo desplegadas en AyniKortex.",
        "expected_category": "Cloud",
    },
    {
        "doc_id": "GOLD-CORT-08",
        "test_type": "corto",
        "title": "Estrategias de Renderizado Híbrido (SSG/SSR) y Optimización de Core Web Vitals en Next.js",
        "content": "Importancia del Rendimiento Web: El posicionamiento orgánico en motores de búsqueda (SEO) y el tiempo percibido de carga (Time to Interactive) son métricas críticas de éxito para la plataforma web principal, la cual sirve como el embudo primario de adquisición de usuarios.\\n\\nImplementación de Frontend: Migramos la arquitectura monolítica de cliente puro (SPA) hacia Next.js 14 utilizando el nuevo paradigma del App Router. Esta transición nos permite combinar componentes de servidor (Server Components) con estrategias avanzadas de generación estática. Aplicamos Incremental Static Regeneration (ISR) para pre-renderizar las páginas de perfiles públicos, sirviéndolas instantáneamente desde los nodos de borde (Edge CDN) de Vercel/CloudFront. Esta aproximación híbrida eliminó los costosos tiempos de carga de Javascript en el dispositivo del cliente, reduciendo drásticamente métricas fundamentales de Core Web Vitals como el Largest Contentful Paint (LCP) a menos de 1 segundo.",
        "expected_category": "Frontend",
    },
    {
        "doc_id": "GOLD-CORT-09",
        "test_type": "corto",
        "title": "Observabilidad Distribuida: Monitoreo Proactivo de Microservicios usando Prometheus y Grafana",
        "content": "Requisito de Operaciones: En un ecosistema distribuido compuesto por docenas de microservicios efímeros, la falta de visibilidad en tiempo real impide la detección temprana de cuellos de botella y errores en cascada que pueden causar interrupciones del servicio.\\n\\nStack de Observabilidad: El equipo de Site Reliability Engineering (SRE) desplegó una infraestructura centralizada de observabilidad basada en Prometheus, que actúa como un motor de series de tiempo para recolectar (hacer scraping) métricas emitidas por los contenedores. Estos datos son visualizados mediante paneles interactivos en Grafana, permitiendo correlacionar métricas de CPU y latencia HTTP. Más importante aún, se han establecido reglas heurísticas en Alertmanager que monitorizan la tasa de errores HTTP 5xx y tiempos de respuesta superiores al p95 (percentil 95), disparando notificaciones automáticas a los canales de Slack del equipo de guardia antes de que el incidente afecte de forma masiva a los usuarios finales.",
        "expected_category": "DevOps",
    },
    {
        "doc_id": "GOLD-CORT-10",
        "test_type": "corto",
        "title": "Arquitectura de Procesamiento ETL Masivo (Big Data) In-Memory utilizando Apache Spark y Hadoop",
        "content": "Desafío Analítico: Diariamente, la plataforma AyniKortex genera terabytes de registros (logs) de auditoría, interacciones de usuarios y métricas de desempeño que deben ser consolidados, depurados y transformados para su análisis en herramientas de Business Intelligence.\\n\\nPipeline de Data Engineering: Para afrontar el volumen y velocidad de los datos, desarrollamos flujos de trabajo (pipelines) de tipo ETL (Extract, Transform, Load) empleando Apache Spark, un motor de procesamiento in-memory distribuido, corriendo sobre un cluster de Hadoop YARN. El pipeline asincrónico lee los datos crudos desde el sistema de archivos HDFS, aplica transformaciones deterministas para limpieza de valores nulos y anonimización de PII (Personally Identifiable Information), y finalmente persiste los datos enriquecidos particionados por fecha en formato columnar Apache Parquet. Esta optimización reduce el espacio de almacenamiento y acelera dramáticamente las consultas analíticas posteriores de agregación.",
        "expected_category": "Data Engineering",
    }
]
