ERRORES_ORTOGRAFICOS = [
    {
        "doc_id": "GOLD-ERR-01",
        "test_type": "errores_ortograficos",
        "title": "Migrasión y Configurasion Avansada de cluster de Kubernets en la nubee de Amazom AWS",
        "content": "Contexto e implemtación: En el proseso de modernisasion de la infraestrutura del proyeto, hemos desidido adoptar la orquestasion de contenedors. Kubernets permite desplegar contenedors Dokker con autoescalado automatico en nodos de computacion AWS de maner facil y rapida. A pesar de los erorres iniciales en la configurasion del ingress controlller, se logro estableser un balanceo de karga sin perder la conexxion de red entre los pods internos del servisio.",
        "expected_category": "Cloud",
    },
    {
        "doc_id": "GOLD-ERR-02",
        "test_type": "errores_ortograficos",
        "title": "Entrenamieto intensivo de redes neuronas y clasificasion automatica de texto en Python",
        "content": "Rechazo de candidattos y evaluacion: El departameto de sencias de datos se enfoco en refinar el algorithmo de porsesamiento natural del lenguage. El modedlo de Machin Learnig alcanza un F1-Skore considerablemete alto al clasifikar documentos usando TF-IDF y regresion logistica. Este entrenamieto profundo se realizo sobre el conjunto de pruebas de validasion, evadiendo los priblemas de sobreajuste (oberfiting) que teniamos en los esenarios anteriores de prduccion.",
        "expected_category": "AI/ML",
    },
    {
        "doc_id": "GOLD-ERR-03",
        "test_type": "errores_ortograficos",
        "title": "Consurco de datos en PostgreSQL y optimisacion esctructural de consutlas SQL masivas",
        "content": "Prooblemas de latensia de datos: En los picos de traficco web, el modulo transasional generaba un cuello de botella terrible. La vandabase de datos Postgresql respnde extramadamente lento cuando no ay indices creados en las colunmas de buskeda principales y las tablas tienen millones de registros sin vacum (limpiesa de memoria muerta). Para solusionarlo, se agrego un indice kompiesto y se reliso una limpesa, logrendo reucir la lektura en un cientopociento de velocidad.",
        "expected_category": "Data Engineering",
    },
    {
        "doc_id": "GOLD-ERR-04",
        "test_type": "errores_ortograficos",
        "title": "Desaroyo optimizado de aplicasiones moviles en Reac Natiove para ecosistema androide",
        "content": "Redisenyo y estrucura de Vistas: Para la nueba bersion del aaplicativo movil, nos decantmos por una arquitedtura basada completametne en componetes. Construimos interfaces de usuario movil con componetes reac y un rigido manejo de esttado global para celulres usando typescript y componentes natibos. Graicas al puente de comunicsaion entre java scritp y codigo maquina, el performase ha megorado incleiblemnete en dispsitivos de gama baga y media.",
        "expected_category": "Mobile",
    },
    {
        "doc_id": "GOLD-ERR-05",
        "test_type": "errores_ortograficos",
        "title": "Sitema de Autenticacion distribuida con toquens JWT y protecsion contra inyecciones SQL",
        "content": "Criticaidad de la civerseguridad: Los ultimos reportes de fallas revelaron vulnerabilidades perimetrales graves. Es completmnete inportante cifrar las claves de aceso de los usuarios y protejer los endpoin de la API contra ataques de hakear e inyecciones de codigo malisioso en los formularios publicos web. Por tal rason, se impemento un filyro asimetrico basado en clyptografia RSA para sersiorarce de la autentiidad de cada peticion del provedor de servisio.",
        "expected_category": "Security",
    },
    {
        "doc_id": "GOLD-ERR-06",
        "test_type": "errores_ortograficos",
        "title": "Creasion modular de APIs REST transacionales en Java Sping Boot y capa Hibernate JPA",
        "content": "Flugo funcional interno de servidor: Para soportar el crecimineto abrumador de interacciones por minuto, abondonamos la arcquitectura bieja. Aora, el contolador prinipal recive la petision HTTP enformato json y guarda el registro permenante en la vase de datos relacional sin erorres manejando las excepciones globales del servidor mediane interseptores y handlers de respuestas predeterminadas. Con sto garntizamos que la capas del beckend parescan mas rapidas a las aplicaciones clintes.",
        "expected_category": "Backend",
    },
    {
        "doc_id": "GOLD-ERR-07",
        "test_type": "errores_ortograficos",
        "title": "Diseñoo y Componentes de la interfaz visual en ReactJS con Typscript y estandares HTML5",
        "content": "Reatividade en el DOM virtal: Al implemntar un modelo puramnete declaratibo, optimizmos los siclos de bida de la aplication de una pagnia (SPA). El rendizado del navegador se actualisa unicamnte cuando cambia el esttado del componete web en el fronend, logrando una experiencia fluida y evirnando recargas de pantalla engorrosas para el usuario final mientrss nanvega por las diferntes vistas interactivs del dashboard general de la paltaforma.",
        "expected_category": "Frontend",
    },
    {
        "doc_id": "GOLD-ERR-08",
        "test_type": "errores_ortograficos",
        "title": "Definicion de Pipeline de integrasion continua en Gitlab CI, Dokker Containers y testeo",
        "content": "Siklo devops y integracion: No se pouede concevir una empreza tegnologica de alt nivel si su eqipo sige compilando los artfatos amano. El nuebo script de automatizasion CI/CD compila la imajen Dokker autonoma y la sube al repositorio de artefactoss simpre y despues de hacer comit o una soolicitud de mescla a la rama principal (mian) del proyecto, asugurando la intgridad del codigo compratido en el repsoitorio centrlizado y proviendo regrecsiones funcionales.",
        "expected_category": "DevOps",
    },
    {
        "doc_id": "GOLD-ERR-09",
        "test_type": "errores_ortograficos",
        "title": "Algoritmo distnaciado de cluterizacion K-Means para agrupar datos transacionales sin etiquetas",
        "content": "Extraccion intelignete de patrone s ocultos: Al recivir bases de dtos masibas sin etiquitar manualmete, se deve utiliazar el apresndisaje no supervizsado. El alghoritmo Kmeans agrupa eficazmente los puntos en un numro epecifico de K centroides calculando con rigo la distancia euclidiana entre las caracteristicass multidiomensionales del dataset sin supervisasion previa o intervecion humna en el porseso matematiko. Asi se destaparon segmntos de usaurios que antes nos pasavan desaparecibidos totalemte.",
        "expected_category": "AI/ML",
    },
    {
        "doc_id": "GOLD-ERR-10",
        "test_type": "errores_ortograficos",
        "title": "Deploy y configuracion de Servidores de almasenamiento en la nube GCP y Azure Storage Buckets",
        "content": "Resilensia geografica de archivos corporativos: Con el avence delas politicas de recuperasion de dsastres (DR), no podemos depneder de un solo disco fijo fisico. Oy en día, guardamos los archivoss estaticos de resguardo (beckups completos) en diveros buquets de almacenamiento en la nubee publica con aceso exclusivamnte privado y politicas de seguridad estrictas que restrinjen el acceso a cuanlquier pesrsona que este fuea d e la red virtal privda d e la emrpesa (VPN).",
        "expected_category": "Cloud",
    }
]
