spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Data Science
datascience.base-url=${DATASCIENCE_BASE_URL:http://localhost:8000}
datascience.connect-timeout=5s
datascience.read-timeout=10s


# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}